name: Black
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python "3.10"
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
