name: mypy
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Python "3.10"
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install mypy
        run: pip install mypy
      - name: Install dependencies
        run: pip install .
      - name: Run mypy
        run: mypy .
